FROM python:3.8.3

# set working directory
RUN mkdir -p /app
WORKDIR /app

# add requirements
COPY ./requirements.txt /app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /app/entrypoint.sh

# add app
COPY . /usr/src/app

# set permissions
RUN ["chmod", "+x", "/app/entrypoint.sh"]

# run server
CMD ["/app/entrypoint.sh"]
