version : '3.7'

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
    image: tryj:client
    ports:
      - '3007:80'
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - REACT_APP_RECAPTCHA_SITE_KEY='6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
      - REQUIRE_RECAPTCHA=false
    depends_on:
      - manager
    links:
      - manager
    stdin_open: true

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    image: tryj:nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - manager
      - client
    # volumes:
      # - data:/etc/letsencrypt

  manager:
    container_name: manager
    build:
      context: ./services/manager
      dockerfile: Dockerfile-prod
    image: tryj:manager
    volumes:
      # - ./services/manager:/app
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=not_so_secret
      - RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
