FROM nginx:1.13.8

RUN rm /etc/nginx/conf.d/default.conf
COPY prod_https.conf /etc/nginx/conf.d

RUN mkdir -p /var/run/nginx
COPY prod_http.conf /var/run/nginx/prod_http.conf

WORKDIR /var/run/nginx
# Copy entrypoint script
COPY ./entrypoint-prod.sh /var/run/nginx/entrypoint-prod.sh

RUN apt-get update
RUN apt-get install -y certbot python-certbot-nginx

CMD ["./entrypoint-prod.sh"]
