#base image
FROM node:lts

# set working directory
WORKDIR /app

# add `usr/src/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@3.4.1 -g

#add app
COPY . ./

CMD ["npm", "start"]
